### ISSUE TITLE
Wrong __init__ function in xsturret_color_tracker

### ISSUE THREAD

**Issue by gsanya** [Interbotix/interbotix_ros_turrets#1]
https://github.com/Interbotix/interbotix_ros_turrets/blob/41f5604e6bd710cd0dd427b6496f3996332dbd79/interbotix_ros_xsturrets/examples/interbotix_xsturret_object_tracker/scripts/xsturret_color_tracker#L36

This call lacks the name argument. it should be:
`self.joint_commands = JointGroupCommand("turret",list(self.joint_states.position))`

Also thanks for the the nice repo.

**Comment by swiz23** [comment]
Thanks for finding this! And appreciate the repo comment :)

The latest commit fixes that issue.
